indent_type = 'Spaces'               # use spaces, not tabs
indent_width = 2                     # exactly two spaces per indent
quote_style = 'AutoPreferSingle'     # use single quotes wherever possible
column_width = 250                   # allow up to 250 chars before wrapping
collapse_simple_statement = 'Always' # collapse simple statements into one line
