AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
Layout/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: error
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false
