# ==============================================================================
# THIS FILE IS GENERATED AUTOMATICALLY
# IT IS COMMITED ONLY ONCE FOR DEMONSTRATION PURPOSES
# ==============================================================================
palette = 'rose-pine-dawn'

[palettes.rose-pine-dawn]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
