palette = "rose-pine-dawn"

# Extracted from upstream Rose Pine Starship palette:
# https://github.com/rose-pine/starship/raw/main/rose-pine-dawn.toml
[palettes.rose-pine-dawn]
overlay = '#f2e9e1'
love = '#b4637a'
gold = '#ea9d34'
rose = '#d7827e'
pine = '#286983'
foam = '#56949f'
iris = '#907aa9'
