plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'autofix/bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit
Naming/RescuedExceptionsVariableName:
  PreferredName: 'err'
Naming/VariableNumber:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false

RSpec/BeEq:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/ArgumentsForwarding:
  UseAnonymousForwarding: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
