palette = "rose-pine-moon"

# Extracted from upstream Rose Pine Starship palette:
# https://github.com/rose-pine/starship/raw/main/rose-pine-moon.toml
[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
