[env]
TERM = 'xterm-256color'

[general]
working_directory = '.dots'
live_config_reload = true
# the whole env theme is managed by the theme script: themes/theme_switcher.rb and its zsh alias 'theme'
import = ["~/.dots/no_stow/themes/active/alacritty.toml"]

[cursor]
style = 'Underline'
unfocused_hollow = true

[font]
size = 16.0

[font.bold]
family = 'Hack Nerd Font'
style = 'Bold'

[font.italic]
# family = 'Lekton Nerd Font Mono'
family = 'Iosevka Nerd Font Mono'
style = 'Italic'

[font.normal]
family = 'SauceCodePro Nerd Font Mono'
style = 'Regular'

[font.offset]
x = 0
y = 2

[scrolling]
history = 99000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal]
shell = { program = '/bin/zsh', args = ['-l'] }

[window]
decorations = 'none'
dynamic_padding = false
startup_mode = 'Fullscreen'
option_as_alt = 'Both'

[window.padding]
x = 10
y = 6
