[env]
TERM="xterm-256color"

[general]
live_config_reload = true
# themes
import = [
  "~/.dots/.config/alacritty/catppuccin-macchiato.toml"
]

[cursor]
style = "Underline"
unfocused_hollow = true

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[window]
decorations = "none"
dynamic_padding = false
startup_mode = "Fullscreen"
option_as_alt = "Both"

[window.padding]
x = 10
y = 0

[keyboard]
bindings = [
  { key = "j", mods = "Command", action = "ToggleViMode" },
]
