# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.7'

group :development, :test do
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
end
